# -*- coding: utf-8 -*-
"""firstcry.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xkqSg17fN1tCPKFvmdEUkH-w0wMVfg1s
"""

import requests
import pandas as pd
from bs4 import BeautifulSoup

response=requests.get("https://www.firstcry.com/bath-toys/5/51?scat=51@@@@@~7797@@@@@1@0@20@@@@@@@@@@&sort=Popularity&ref2=menu_dd_bath_squeeze-toys_H")
print(response)

soup=BeautifulSoup(response.content,"html.parser")
#print(soup)
names=soup.find_all('div',class_="li_txt1 wifi lft R13_42")
name=[]
for i in names[1:len(names)+1]:
  name.append(i.get_text())
#print(name)

prices=soup.find_all('span',class_="r1 B14_42")
price=[]
for i in prices[1:len(names)+1]:
  price.append(i.get_text())
#print(price)

discounts=soup.find_all('a',class_="R12_red")
discount=[]
for i in discounts[1:len(names)+1]:
  discount.append(i.get_text())
#print(discount)

stars=soup.find_all('div',class_="small_star")
star=[]
for i in stars[1:len(names)+1]:
  d=i.span['data-rate']
  star.append(d)
#print(star)

links=soup.find_all('div',class_="list_img wifi")
link=[]
for i in links[1:len(names)+1]:
  link.append(i.a['href'])
#print(link)

images=soup.find_all('div',class_='list_img wifi')
image=[]
for i in images[1:len(names)+1]:
  d="https:"+i.img['src']
  image.append(d)
#print(image)

data={
    "Names":pd.Series(name),
    "Price":pd.Series(price),
    "Discount":pd.Series(discount),
    "Stars":pd.Series(star),
    "Images":pd.Series(image),
    "Links":pd.Series(link),
}
#print(data)
df=pd.DataFrame(data)
#print(df)
df.to_csv("Firstcry_toys.csv")

"""# New Section"""